import type { User, Opportunity, Alert, NewsEvent, Customer } from './types';

export const users: User[] = [
  { uid: 'user-1', displayName: 'Anna Kovács', email: 'anna.kovacs@colonygo.com', role: 'sales', photoURL: 'https://picsum.photos/seed/user1/40/40', initials: 'AK' },
  { uid: 'user-2', displayName: 'Luca Moretti', email: 'luca.moretti@colonygo.com', role: 'sales', photoURL: 'https://picsum.photos/seed/user2/40/40', initials: 'LM' },
  { uid: 'user-3', displayName: 'Laura Schmidt', email: 'laura.schmidt@colonygo.com', role: 'sales', photoURL: 'https://picsum.photos/seed/user3/40/40', initials: 'LS' },
  { uid: 'user-4', displayName: 'Elena Rossi', email: 'elena.rossi@colonygo.com', role: 'sales', photoURL: 'https://picsum.photos/seed/user4/40/40', initials: 'ER' },
  { uid: 'user-5', displayName: 'Omar Haddad', email: 'omar.haddad@colonygo.com', role: 'manager', photoURL: 'https://picsum.photos/seed/user5/40/40', initials: 'OH' },
  { uid: 'user-6', displayName: 'Marc Dupont', email: 'marc.dupont@colonygo.com', role: 'admin', photoURL: 'https://picsum.photos/seed/user6/40/40', initials: 'MD' },
];

export const customers: Customer[] = [
    { id: 'CS-AWS-001', name: 'Amazon Web Services', company: 'Amazon Web Services', sector: 'Cloud', avatarUrl: 'https://picsum.photos/seed/client1/40/40', initials: 'AW' },
    { id: 'CS-CAPG-003', name: 'Capgemini', company: 'Capgemini', sector: 'Consulting', avatarUrl: 'https://picsum.photos/seed/client2/40/40', initials: 'C' },
    { id: 'CS-BNP-006', name: 'BNP Paribas', company: 'BNP Paribas', sector: 'Finance', avatarUrl: 'https://picsum.photos/seed/client3/40/40', initials: 'BNP' },
    { id: 'CS-CISCO-007', name: 'Cisco Systems', company: 'Cisco Systems', sector: 'Networking', avatarUrl: 'https://picsum.photos/seed/client4/40/40', initials: 'CS' },
    { id: 'CS-GCP-013', name: 'Google Cloud', company: 'Google Cloud', sector: 'Cloud', avatarUrl: 'https://picsum.photos/seed/client5/40/40', initials: 'GC' },
    { id: 'CS-SFR-014', name: 'SFR Business', company: 'SFR Business', sector: 'Telecom', avatarUrl: 'https://picsum.photos/seed/client6/40/40', initials: 'SB' },
    { id: 'CS-HWE-015', name: 'Huawei Enterprise', company: 'Huawei Enterprise', sector: 'Hardware', avatarUrl: 'https://picsum.photos/seed/client7/40/40', initials: 'HE' },
    { id: 'CS-OBS-019', name: 'Orange Business Services', company: 'Orange Business Services', sector: 'Telecom', avatarUrl: 'https://picsum.photos/seed/client8/40/40', initials: 'OB' },
    { id: 'CS-SG-036', name: 'Société Générale', company: 'Société Générale', sector: 'Finance', avatarUrl: 'https://picsum.photos/seed/client9/40/40', initials: 'SG' },
    { id: 'CS-DELL-045', name: 'Dell Technologies', company: 'Dell Technologies', sector: 'Hardware', avatarUrl: 'https://picsum.photos/seed/client10/40/40', initials: 'DT' },
];

export const opportunities: Opportunity[] = [
  {
    id: 'OPP-00001',
    opportunityname: 'Cloud Migration & Infrastructure Upgrade',
    opportunitydescription: 'Full migration of on-premise servers to AWS cloud.',
    customerid: 'CS-AWS-001',
    customername: 'Amazon Web Services',
    opportunitystatut: 'Start',
    opportunityphase: 'Deal',
    hardware_price: 50000,
    software_price: 75000,
    service_price: 100000,
    opportunityowner: 'Anna Kovács',
    swot_strength: 5,
    swot_weakness: 2,
    swot_opportunities: 4,
    swot_threats: 3,
    value_forecast: 225000,
    value_final: 220000,
    value_discount: 5000,
    value_budget: 250000,
    value_customer: 230000,
    value_bonus: 0,
    opportunityscl: 'Technical Acceptance Payment:50%; Design Approval Payment:50%',
    ownerDetails: users.find(u => u.displayName === 'Anna Kovács'),
  },
  {
    id: 'OPP-00002',
    opportunityname: 'Digital Transformation Consulting',
    opportunitydescription: 'Consulting services for digital strategy.',
    customerid: 'CS-CAPG-003',
    customername: 'Capgemini',
    opportunitystatut: 'Forecast',
    opportunityphase: 'Discovery',
    hardware_price: 0,
    software_price: 20000,
    service_price: 180000,
    opportunityowner: 'Luca Moretti',
    swot_strength: 4,
    swot_weakness: 3,
    swot_opportunities: 5,
    swot_threats: 2,
    value_forecast: 200000,
    value_final: 0,
    value_discount: 0,
    value_budget: 210000,
    value_customer: 200000,
    value_bonus: 0,
    opportunityscl: 'Design Approval Payment:100%',
    ownerDetails: users.find(u => u.displayName === 'Luca Moretti'),
  },
   {
    id: 'OPP-00003',
    opportunityname: 'Security Infrastructure Overhaul',
    opportunitydescription: 'Network security hardware and software.',
    customerid: 'CS-CISCO-007',
    customername: 'Cisco Systems',
    opportunitystatut: 'Stop',
    opportunityphase: 'Evaluation',
    hardware_price: 150000,
    software_price: 100000,
    service_price: 50000,
    opportunityowner: 'Laura Schmidt',
    swot_strength: 3,
    swot_weakness: 4,
    swot_opportunities: 3,
    swot_threats: 4,
    value_forecast: 300000,
    value_final: 0,
    value_discount: 20000,
    value_budget: 320000,
    value_customer: 280000,
    value_bonus: 0,
    opportunityscl: 'Technical Acceptance Payment:70%; Design Approval Payment:30%',
    ownerDetails: users.find(u => u.displayName === 'Laura Schmidt'),
  },
   {
    id: 'OPP-00004',
    opportunityname: 'AI Analytics Platform',
    opportunitydescription: 'Deploy Google Cloud AI tools.',
    customerid: 'CS-GCP-013',
    customername: 'Google Cloud',
    opportunitystatut: 'Start',
    opportunityphase: 'Deal',
    hardware_price: 10000,
    software_price: 300000,
    service_price: 90000,
    opportunityowner: 'Elena Rossi',
    swot_strength: 5,
    swot_weakness: 1,
    swot_opportunities: 5,
    swot_threats: 2,
    value_forecast: 400000,
    value_final: 400000,
    value_discount: 0,
    value_budget: 400000,
    value_customer: 400000,
    value_bonus: 10000,
    opportunityscl: 'Final Payment:100%',
    ownerDetails: users.find(u => u.displayName === 'Elena Rossi'),
  },
   {
    id: 'OPP-00005',
    opportunityname: '5G Network Equipment',
    opportunitydescription: 'New hardware for 5G rollout.',
    customerid: 'CS-SFR-014',
    customername: 'SFR Business',
    opportunitystatut: 'Cancelled',
    opportunityphase: 'Prospection',
    hardware_price: 1000000,
    software_price: 50000,
    service_price: 150000,
    opportunityowner: 'Omar Haddad',
    swot_strength: 2,
    swot_weakness: 5,
    swot_opportunities: 2,
    swot_threats: 5,
    value_forecast: 1200000,
    value_final: 0,
    value_discount: 0,
    value_budget: 1500000,
    value_customer: 1200000,
    value_bonus: 0,
    opportunityscl: 'Initial Payment:20%; Final Payment:80%',
    ownerDetails: users.find(u => u.displayName === 'Omar Haddad'),
  }
];

// Mock data, to be replaced with dynamic data later
export const alerts = [
  {
    id: 'alert-1',
    opportunityId: "OPP-00003",
    opportunityName: 'Security Infrastructure Overhaul',
    ownerName: 'Laura Schmidt',
    reason: "Opportunité bloquée depuis 15 jours",
    severity: "urgent",
  },
  {
    id: 'alert-2',
    opportunityId: "OPP-00002",
    opportunityName: 'Digital Transformation Consulting',
    ownerName: 'Luca Moretti',
    reason: "Marge négative détectée",
    severity: "warning",
  },
];

export const newsFeed = [
    {
        id: 'news-1',
        opportunityId: "OPP-00001",
        clientName: "Amazon Web Services",
        ownerName: "Anna Kovács",
        eventType: "phase_changed",
        eventName: "Phase passée de Evaluation à Deal",
        createdAt: "2024-05-23T10:00:00Z"
    },
    {
        id: 'news-2',
        opportunityId: "OPP-00004",
        clientName: "Google Cloud",
        ownerName: "Elena Rossi",
        eventType: "status_updated",
        eventName: "Statut changé en Start",
        createdAt: "2024-05-23T11:00:00Z"
    }
];

export const salesPipelineData = [
  { name: 'Prospection', value: 1 },
  { name: 'Discovery', value: 1 },
  { name: 'Evaluation', value: 1 },
  { name: 'Deal', value: 2 },
];
