/* eslint-disable */
// Auto-generated from Excel Dummydata sheet (026dc3bf-5815-4d4e-88b8-05a11134212c.xlsx)
// Do not edit manually.

export const excelOpportunities = [
  {
    "opportunityid": "OPP-00001",
    "opportunityname": "IoT Building Integration – Phase 4",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-AWS-001",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Cancelled",
    "hardware_price": 65434,
    "software_price": 14159,
    "service_price": 60343,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Anna Kovács",
    "swot_strength": 5,
    "swot_weakness": 4,
    "swot_opportunities": 4,
    "swot_threats": 4,
    "value_forecast": 145706,
    "value_final": 139936,
    "value_discount": 1660,
    "value_budget": 133259,
    "value_customer": 139936,
    "value_bonus": 530,
    "opportunityscl": "Technical Acceptance Payment:31%; Design Approval Payment:69%"
  },
  {
    "opportunityid": "OPP-00002",
    "opportunityname": "Cybersecurity Upgrade – Phase 4",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-AWS-002",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Start",
    "hardware_price": 7719,
    "software_price": 79056,
    "service_price": 17907,
    "opportunityphase": "Prospection",
    "opportunityowner": "Luca Moretti",
    "swot_strength": 5,
    "swot_weakness": 3,
    "swot_opportunities": 1,
    "swot_threats": 2,
    "value_forecast": 110644,
    "value_final": 104682,
    "value_discount": 2821,
    "value_budget": 104586,
    "value_customer": 104682,
    "value_bonus": 402,
    "opportunityscl": "Integration & Configuration Payment:3%; Technical Acceptance Payment:35%; Delivery Payment:27%; Down Payment:35%"
  },
  {
    "opportunityid": "OPP-00003",
    "opportunityname": "SD-WAN Deployment – Phase 1",
    "opportunitydescription": "Modernizing core systems to enhance operational efficiency.",
    "customerid": "CS-CAPG-003",
    "customername": "Capgemini",
    "opportunitystatut": "Forecast",
    "hardware_price": 28069,
    "software_price": 32645,
    "service_price": 11253,
    "opportunityphase": "Prospection",
    "opportunityowner": "Laura Schmidt",
    "swot_strength": 1,
    "swot_weakness": 5,
    "swot_opportunities": 4,
    "swot_threats": 1,
    "value_forecast": 72654,
    "value_final": 71967,
    "value_discount": 1256,
    "value_budget": 71912,
    "value_customer": 71967,
    "value_bonus": 858,
    "opportunityscl": "Installation Completion:41%; Delivery Payment:9%; Final Acceptance:37%; Technical Acceptance Payment:13%"
  },
  {
    "opportunityid": "OPP-00004",
    "opportunityname": "Cloud Migration – Phase 1",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-CAPG-004",
    "customername": "Capgemini",
    "opportunitystatut": "Forecast",
    "hardware_price": 26621,
    "software_price": 86436,
    "service_price": 84512,
    "opportunityphase": "Discovery",
    "opportunityowner": "Elena Rossi",
    "swot_strength": 5,
    "swot_weakness": 2,
    "swot_opportunities": 5,
    "swot_threats": 1,
    "value_forecast": 198763,
    "value_final": 197569,
    "value_discount": 2281,
    "value_budget": 196765,
    "value_customer": 197569,
    "value_bonus": 2316,
    "opportunityscl": "Delivery Payment:79%; Down Payment:21%"
  },
  {
    "opportunityid": "OPP-00005",
    "opportunityname": "Hybrid Cloud Deployment – Phase 1",
    "opportunitydescription": "Rollout of infrastructure modernization across multiple sites.",
    "customerid": "CS-AWS-005",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Forecast",
    "hardware_price": 62147,
    "software_price": 67022,
    "service_price": 103235,
    "opportunityphase": "Deal",
    "opportunityowner": "Omar Haddad",
    "swot_strength": 5,
    "swot_weakness": 2,
    "swot_opportunities": 4,
    "swot_threats": 2,
    "value_forecast": 236828,
    "value_final": 232404,
    "value_discount": 3638,
    "value_budget": 228241,
    "value_customer": 232404,
    "value_bonus": 30,
    "opportunityscl": "Material Procurement Payment:17%; Final Acceptance:37%; Delivery Payment:46%"
  },
  {
    "opportunityid": "OPP-00006",
    "opportunityname": "SD-WAN Deployment – Phase 1",
    "opportunitydescription": "Implementing cybersecurity best practices and identity protections.",
    "customerid": "CS-BNP-006",
    "customername": "BNP Paribas",
    "opportunitystatut": "Forecast",
    "hardware_price": 80654,
    "software_price": 14633,
    "service_price": 80667,
    "opportunityphase": "Discovery",
    "opportunityowner": "Anna Kovács",
    "swot_strength": 3,
    "swot_weakness": 3,
    "swot_opportunities": 2,
    "swot_threats": 3,
    "value_forecast": 179565,
    "value_final": 175954,
    "value_discount": 2568,
    "value_budget": 174506,
    "value_customer": 175954,
    "value_bonus": 2118,
    "opportunityscl": "Design Approval Payment:14%; Delivery Payment:12%; Installation Completion:6%; Material Procurement Payment:68%"
  },
  {
    "opportunityid": "OPP-00007",
    "opportunityname": "Hybrid Cloud Deployment – Phase 2",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-CISCO-007",
    "customername": "Cisco Systems",
    "opportunitystatut": "Start",
    "hardware_price": 18381,
    "software_price": 59209,
    "service_price": 11858,
    "opportunityphase": "Discovery",
    "opportunityowner": "Youssef El-Haddad",
    "swot_strength": 1,
    "swot_weakness": 3,
    "swot_opportunities": 3,
    "swot_threats": 4,
    "value_forecast": 96421,
    "value_final": 89448,
    "value_discount": 1994,
    "value_budget": 84821,
    "value_customer": 89448,
    "value_bonus": 2499,
    "opportunityscl": "Technical Acceptance Payment:100%; Final Acceptance:0%"
  },
  {
    "opportunityid": "OPP-00008",
    "opportunityname": "Compute Cluster Expansion – Phase 3",
    "opportunitydescription": "Deployment of scalable infrastructure for improved performance.",
    "customerid": "CS-CAPG-008",
    "customername": "Capgemini",
    "opportunitystatut": "Start",
    "hardware_price": 52110,
    "software_price": 43205,
    "service_price": 58768,
    "opportunityphase": "Deal",
    "opportunityowner": "Luca Moretti",
    "swot_strength": 3,
    "swot_weakness": 4,
    "swot_opportunities": 2,
    "swot_threats": 1,
    "value_forecast": 157820,
    "value_final": 154083,
    "value_discount": 2706,
    "value_budget": 147195,
    "value_customer": 154083,
    "value_bonus": 1081,
    "opportunityscl": "Delivery Payment:43%; Installation Completion:3%; Integration & Configuration Payment:7%; Material Procurement Payment:47%"
  },
  {
    "opportunityid": "OPP-00009",
    "opportunityname": "Compute Cluster Expansion – Phase 3",
    "opportunitydescription": "Strengthening cloud security and zero trust compliance.",
    "customerid": "CS-AWS-009",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Forecast",
    "hardware_price": 127979,
    "software_price": 81491,
    "service_price": 8498,
    "opportunityphase": "Discovery",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 1,
    "swot_weakness": 3,
    "swot_opportunities": 1,
    "swot_threats": 5,
    "value_forecast": 220632,
    "value_final": 217968,
    "value_discount": 300,
    "value_budget": 216696,
    "value_customer": 217968,
    "value_bonus": 949,
    "opportunityscl": "Down Payment:41%; Integration & Configuration Payment:0%; Material Procurement Payment:6%; Installation Completion:53%"
  },
  {
    "opportunityid": "OPP-00010",
    "opportunityname": "Cloud Migration – Phase 4",
    "opportunitydescription": "Modernizing core systems to enhance operational efficiency.",
    "customerid": "CS-CAPG-010",
    "customername": "Capgemini",
    "opportunitystatut": "Cancelled",
    "hardware_price": 86997,
    "software_price": 42716,
    "service_price": 23950,
    "opportunityphase": "Deal",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 4,
    "swot_weakness": 4,
    "swot_opportunities": 4,
    "swot_threats": 1,
    "value_forecast": 153876,
    "value_final": 153663,
    "value_discount": 72,
    "value_budget": 150646,
    "value_customer": 153663,
    "value_bonus": 2142,
    "opportunityscl": "Down Payment:16%; Installation Completion:22%; Delivery Payment:16%; Design Approval Payment:46%"
  },
  {
    "opportunityid": "OPP-00011",
    "opportunityname": "Cybersecurity Upgrade – Phase 1",
    "opportunitydescription": "Integration of multi-cloud workloads and automation pipelines.",
    "customerid": "CS-BNP-011",
    "customername": "BNP Paribas",
    "opportunitystatut": "Stop",
    "hardware_price": 65303,
    "software_price": 89858,
    "service_price": 118855,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Youssef El-Haddad",
    "swot_strength": 2,
    "swot_weakness": 3,
    "swot_opportunities": 4,
    "swot_threats": 2,
    "value_forecast": 278008,
    "value_final": 274016,
    "value_discount": 1097,
    "value_budget": 272965,
    "value_customer": 274016,
    "value_bonus": 1518,
    "opportunityscl": "Integration & Configuration Payment:83%; Final Acceptance:17%"
  },
  {
    "opportunityid": "OPP-00012",
    "opportunityname": "Hybrid Cloud Deployment – Phase 2",
    "opportunitydescription": "Full upgrade of networking equipment and routing policies.",
    "customerid": "CS-AWS-012",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Start",
    "hardware_price": 142239,
    "software_price": 68607,
    "service_price": 38488,
    "opportunityphase": "Deal",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 3,
    "swot_weakness": 5,
    "swot_opportunities": 2,
    "swot_threats": 4,
    "value_forecast": 253544,
    "value_final": 249334,
    "value_discount": 407,
    "value_budget": 249320,
    "value_customer": 249334,
    "value_bonus": 1458,
    "opportunityscl": "Delivery Payment:64%; Down Payment:1%; Technical Acceptance Payment:2%; Material Procurement Payment:33%"
  },
  {
    "opportunityid": "OPP-00013",
    "opportunityname": "SD-WAN Deployment – Phase 2",
    "opportunitydescription": "Full upgrade of networking equipment and routing policies.",
    "customerid": "CS-GCP-013",
    "customername": "Google Cloud",
    "opportunitystatut": "Forecast",
    "hardware_price": 147721,
    "software_price": 62148,
    "service_price": 50776,
    "opportunityphase": "Discovery",
    "opportunityowner": "Youssef El-Haddad",
    "swot_strength": 5,
    "swot_weakness": 2,
    "swot_opportunities": 5,
    "swot_threats": 1,
    "value_forecast": 262173,
    "value_final": 260645,
    "value_discount": 266,
    "value_budget": 254397,
    "value_customer": 260645,
    "value_bonus": 2142,
    "opportunityscl": "Delivery Payment:43%; Final Acceptance:37%; Down Payment:19%"
  },
  {
    "opportunityid": "OPP-00014",
    "opportunityname": "Cloud Migration – Phase 4",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-SFR-014",
    "customername": "SFR Business",
    "opportunitystatut": "Stop",
    "hardware_price": 63902,
    "software_price": 83214,
    "service_price": 9076,
    "opportunityphase": "Discovery",
    "opportunityowner": "Nadia Cherif",
    "swot_strength": 2,
    "swot_weakness": 3,
    "swot_opportunities": 2,
    "swot_threats": 5,
    "value_forecast": 161146,
    "value_final": 156192,
    "value_discount": 3381,
    "value_budget": 153952,
    "value_customer": 156192,
    "value_bonus": 1435,
    "opportunityscl": "Installation Completion:20%; Technical Acceptance Payment:77%; Delivery Payment:3%"
  },
  {
    "opportunityid": "OPP-00015",
    "opportunityname": "Cybersecurity Upgrade – Phase 2",
    "opportunitydescription": "Full upgrade of networking equipment and routing policies.",
    "customerid": "CS-HWE-015",
    "customername": "Huawei Enterprise",
    "opportunitystatut": "Start",
    "hardware_price": 26787,
    "software_price": 63036,
    "service_price": 70887,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Laura Schmidt",
    "swot_strength": 1,
    "swot_weakness": 5,
    "swot_opportunities": 3,
    "swot_threats": 1,
    "value_forecast": 162468,
    "value_final": 160710,
    "value_discount": 2351,
    "value_budget": 157856,
    "value_customer": 160710,
    "value_bonus": 1258,
    "opportunityscl": "Down Payment:19%; Final Acceptance:81%"
  },
  {
    "opportunityid": "OPP-00016",
    "opportunityname": "Hybrid Cloud Deployment – Phase 2",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-BNP-016",
    "customername": "BNP Paribas",
    "opportunitystatut": "Stop",
    "hardware_price": 17299,
    "software_price": 72438,
    "service_price": 19840,
    "opportunityphase": "Prospection",
    "opportunityowner": "Sofia Benali",
    "swot_strength": 3,
    "swot_weakness": 5,
    "swot_opportunities": 2,
    "swot_threats": 2,
    "value_forecast": 112431,
    "value_final": 109577,
    "value_discount": 3039,
    "value_budget": 102826,
    "value_customer": 109577,
    "value_bonus": 1866,
    "opportunityscl": "Down Payment:40%; Installation Completion:60%"
  },
  {
    "opportunityid": "OPP-00017",
    "opportunityname": "Cybersecurity Upgrade – Phase 2",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-GCP-017",
    "customername": "Google Cloud",
    "opportunitystatut": "Stop",
    "hardware_price": 37062,
    "software_price": 68019,
    "service_price": 114129,
    "opportunityphase": "Deal",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 3,
    "swot_weakness": 5,
    "swot_opportunities": 1,
    "swot_threats": 1,
    "value_forecast": 224053,
    "value_final": 219210,
    "value_discount": 371,
    "value_budget": 216059,
    "value_customer": 219210,
    "value_bonus": 1101,
    "opportunityscl": "Design Approval Payment:14%; Technical Acceptance Payment:86%"
  },
  {
    "opportunityid": "OPP-00018",
    "opportunityname": "Network Backbone Upgrade – Phase 1",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-HWE-018",
    "customername": "Huawei Enterprise",
    "opportunitystatut": "Start",
    "hardware_price": 46718,
    "software_price": 33911,
    "service_price": 53103,
    "opportunityphase": "Deal",
    "opportunityowner": "Laura Schmidt",
    "swot_strength": 5,
    "swot_weakness": 4,
    "swot_opportunities": 3,
    "swot_threats": 1,
    "value_forecast": 135842,
    "value_final": 133732,
    "value_discount": 3538,
    "value_budget": 127316,
    "value_customer": 133732,
    "value_bonus": 719,
    "opportunityscl": "Installation Completion:70%; Final Acceptance:9%; Technical Acceptance Payment:21%"
  },
  {
    "opportunityid": "OPP-00019",
    "opportunityname": "IoT Building Integration – Phase 4",
    "opportunitydescription": "Implementing cybersecurity best practices and identity protections.",
    "customerid": "CS-OBS-019",
    "customername": "Orange Business Services",
    "opportunitystatut": "Start",
    "hardware_price": 63947,
    "software_price": 84524,
    "service_price": 60173,
    "opportunityphase": "Discovery",
    "opportunityowner": "Elena Rossi",
    "swot_strength": 2,
    "swot_weakness": 1,
    "swot_opportunities": 5,
    "swot_threats": 1,
    "value_forecast": 210688,
    "value_final": 208644,
    "value_discount": 684,
    "value_budget": 205618,
    "value_customer": 208644,
    "value_bonus": 2042,
    "opportunityscl": "Final Acceptance:70%; Down Payment:30%"
  },
  {
    "opportunityid": "OPP-00020",
    "opportunityname": "Storage Platform Upgrade – Phase 3",
    "opportunitydescription": "Strengthening cloud security and zero trust compliance.",
    "customerid": "CS-GCP-020",
    "customername": "Google Cloud",
    "opportunitystatut": "Start",
    "hardware_price": 106626,
    "software_price": 46094,
    "service_price": 51441,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 5,
    "swot_weakness": 3,
    "swot_opportunities": 4,
    "swot_threats": 1,
    "value_forecast": 207294,
    "value_final": 204161,
    "value_discount": 625,
    "value_budget": 203553,
    "value_customer": 204161,
    "value_bonus": 1100,
    "opportunityscl": "Installation Completion:1%; Integration & Configuration Payment:61%; Final Acceptance:11%; Material Procurement Payment:27%"
  },
  {
    "opportunityid": "OPP-00021",
    "opportunityname": "Storage Platform Upgrade – Phase 3",
    "opportunitydescription": "Implementing cybersecurity best practices and identity protections.",
    "customerid": "CS-OBS-021",
    "customername": "Orange Business Services",
    "opportunitystatut": "Start",
    "hardware_price": 45781,
    "software_price": 57918,
    "service_price": 9268,
    "opportunityphase": "Deal",
    "opportunityowner": "Hugo Martin",
    "swot_strength": 1,
    "swot_weakness": 5,
    "swot_opportunities": 4,
    "swot_threats": 1,
    "value_forecast": 118814,
    "value_final": 112967,
    "value_discount": 890,
    "value_budget": 112020,
    "value_customer": 112967,
    "value_bonus": 1131,
    "opportunityscl": "Technical Acceptance Payment:38%; Delivery Payment:62%"
  },
  {
    "opportunityid": "OPP-00022",
    "opportunityname": "Cybersecurity Upgrade – Phase 2",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-CISCO-022",
    "customername": "Cisco Systems",
    "opportunitystatut": "Cancelled",
    "hardware_price": 87340,
    "software_price": 45034,
    "service_price": 13896,
    "opportunityphase": "Prospection",
    "opportunityowner": "Laura Schmidt",
    "swot_strength": 5,
    "swot_weakness": 1,
    "swot_opportunities": 2,
    "swot_threats": 2,
    "value_forecast": 152121,
    "value_final": 146270,
    "value_discount": 2223,
    "value_budget": 142377,
    "value_customer": 146270,
    "value_bonus": 1097,
    "opportunityscl": "Final Acceptance:39%; Down Payment:28%; Design Approval Payment:11%; Installation Completion:23%"
  },
  {
    "opportunityid": "OPP-00023",
    "opportunityname": "SD-WAN Deployment – Phase 4",
    "opportunitydescription": "Full upgrade of networking equipment and routing policies.",
    "customerid": "CS-BNP-023",
    "customername": "BNP Paribas",
    "opportunitystatut": "Forecast",
    "hardware_price": 111078,
    "software_price": 87545,
    "service_price": 82937,
    "opportunityphase": "Discovery",
    "opportunityowner": "Sofia Benali",
    "swot_strength": 5,
    "swot_weakness": 2,
    "swot_opportunities": 1,
    "swot_threats": 4,
    "value_forecast": 285060,
    "value_final": 281560,
    "value_discount": 1276,
    "value_budget": 275320,
    "value_customer": 281560,
    "value_bonus": 968,
    "opportunityscl": "Down Payment:69%; Delivery Payment:17%; Design Approval Payment:14%"
  },
  {
    "opportunityid": "OPP-00024",
    "opportunityname": "Storage Platform Upgrade – Phase 2",
    "opportunitydescription": "Migration of workloads to hybrid cloud environments.",
    "customerid": "CS-CISCO-024",
    "customername": "Cisco Systems",
    "opportunitystatut": "Forecast",
    "hardware_price": 119755,
    "software_price": 49319,
    "service_price": 24637,
    "opportunityphase": "Prospection",
    "opportunityowner": "Elena Rossi",
    "swot_strength": 5,
    "swot_weakness": 2,
    "swot_opportunities": 2,
    "swot_threats": 2,
    "value_forecast": 199857,
    "value_final": 193711,
    "value_discount": 1739,
    "value_budget": 190176,
    "value_customer": 193711,
    "value_bonus": 475,
    "opportunityscl": "Integration & Configuration Payment:17%; Technical Acceptance Payment:20%; Down Payment:47%; Delivery Payment:16%"
  },
  {
    "opportunityid": "OPP-00025",
    "opportunityname": "Storage Platform Upgrade – Phase 4",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-BNP-025",
    "customername": "BNP Paribas",
    "opportunitystatut": "Forecast",
    "hardware_price": 118871,
    "software_price": 21494,
    "service_price": 29733,
    "opportunityphase": "Discovery",
    "opportunityowner": "Omar Haddad",
    "swot_strength": 2,
    "swot_weakness": 4,
    "swot_opportunities": 3,
    "swot_threats": 5,
    "value_forecast": 176418,
    "value_final": 170098,
    "value_discount": 2156,
    "value_budget": 168678,
    "value_customer": 170098,
    "value_bonus": 1838,
    "opportunityscl": "Technical Acceptance Payment:62%; Down Payment:38%"
  },
  {
    "opportunityid": "OPP-00026",
    "opportunityname": "IoT Building Integration – Phase 1",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-OBS-026",
    "customername": "Orange Business Services",
    "opportunitystatut": "Start",
    "hardware_price": 16300,
    "software_price": 18290,
    "service_price": 63878,
    "opportunityphase": "Deal",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 4,
    "swot_weakness": 5,
    "swot_opportunities": 4,
    "swot_threats": 2,
    "value_forecast": 101024,
    "value_final": 98468,
    "value_discount": 536,
    "value_budget": 98022,
    "value_customer": 98468,
    "value_bonus": 84,
    "opportunityscl": "Design Approval Payment:24%; Integration & Configuration Payment:10%; Final Acceptance:66%"
  },
  {
    "opportunityid": "OPP-00027",
    "opportunityname": "Data Center Modernization – Phase 2",
    "opportunitydescription": "Rollout of infrastructure modernization across multiple sites.",
    "customerid": "CS-OBS-027",
    "customername": "Orange Business Services",
    "opportunitystatut": "Cancelled",
    "hardware_price": 49545,
    "software_price": 17180,
    "service_price": 10396,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 4,
    "swot_weakness": 4,
    "swot_opportunities": 5,
    "swot_threats": 1,
    "value_forecast": 83191,
    "value_final": 77121,
    "value_discount": 1965,
    "value_budget": 73339,
    "value_customer": 77121,
    "value_bonus": 1950,
    "opportunityscl": "Material Procurement Payment:35%; Delivery Payment:16%; Design Approval Payment:49%"
  },
  {
    "opportunityid": "OPP-00028",
    "opportunityname": "Cybersecurity Upgrade – Phase 4",
    "opportunitydescription": "Integration of multi-cloud workloads and automation pipelines.",
    "customerid": "CS-BNP-028",
    "customername": "BNP Paribas",
    "opportunitystatut": "Start",
    "hardware_price": 101139,
    "software_price": 70369,
    "service_price": 68044,
    "opportunityphase": "Discovery",
    "opportunityowner": "Hugo Martin",
    "swot_strength": 3,
    "swot_weakness": 4,
    "swot_opportunities": 4,
    "swot_threats": 3,
    "value_forecast": 243092,
    "value_final": 239552,
    "value_discount": 200,
    "value_budget": 238800,
    "value_customer": 239552,
    "value_bonus": 1174,
    "opportunityscl": "Final Acceptance:37%; Integration & Configuration Payment:25%; Technical Acceptance Payment:39%"
  },
  {
    "opportunityid": "OPP-00029",
    "opportunityname": "Smart Facility Project – Phase 1",
    "opportunitydescription": "Full upgrade of networking equipment and routing policies.",
    "customerid": "CS-HWE-029",
    "customername": "Huawei Enterprise",
    "opportunitystatut": "Cancelled",
    "hardware_price": 21200,
    "software_price": 69618,
    "service_price": 115532,
    "opportunityphase": "Prospection",
    "opportunityowner": "Youssef El-Haddad",
    "swot_strength": 5,
    "swot_weakness": 1,
    "swot_opportunities": 5,
    "swot_threats": 5,
    "value_forecast": 211381,
    "value_final": 206350,
    "value_discount": 3897,
    "value_budget": 204826,
    "value_customer": 206350,
    "value_bonus": 1809,
    "opportunityscl": "Down Payment:10%; Delivery Payment:90%"
  },
  {
    "opportunityid": "OPP-00030",
    "opportunityname": "Data Center Modernization – Phase 4",
    "opportunitydescription": "Migration of workloads to hybrid cloud environments.",
    "customerid": "CS-SFR-030",
    "customername": "SFR Business",
    "opportunitystatut": "Forecast",
    "hardware_price": 116032,
    "software_price": 65589,
    "service_price": 42351,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Anna Kovács",
    "swot_strength": 5,
    "swot_weakness": 3,
    "swot_opportunities": 5,
    "swot_threats": 2,
    "value_forecast": 227984,
    "value_final": 223972,
    "value_discount": 2561,
    "value_budget": 220287,
    "value_customer": 223972,
    "value_bonus": 2385,
    "opportunityscl": "Material Procurement Payment:60%; Installation Completion:40%"
  },
  {
    "opportunityid": "OPP-00031",
    "opportunityname": "Storage Platform Upgrade – Phase 4",
    "opportunitydescription": "Strengthening cloud security and zero trust compliance.",
    "customerid": "CS-CISCO-031",
    "customername": "Cisco Systems",
    "opportunitystatut": "Forecast",
    "hardware_price": 144092,
    "software_price": 80793,
    "service_price": 34730,
    "opportunityphase": "Prospection",
    "opportunityowner": "Omar Haddad",
    "swot_strength": 2,
    "swot_weakness": 3,
    "swot_opportunities": 4,
    "swot_threats": 4,
    "value_forecast": 264445,
    "value_final": 259615,
    "value_discount": 1998,
    "value_budget": 257163,
    "value_customer": 259615,
    "value_bonus": 1413,
    "opportunityscl": "Down Payment:90%; Integration & Configuration Payment:10%"
  },
  {
    "opportunityid": "OPP-00032",
    "opportunityname": "Smart Facility Project – Phase 1",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-BNP-032",
    "customername": "BNP Paribas",
    "opportunitystatut": "Start",
    "hardware_price": 107249,
    "software_price": 42789,
    "service_price": 13082,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Anna Kovács",
    "swot_strength": 5,
    "swot_weakness": 5,
    "swot_opportunities": 4,
    "swot_threats": 3,
    "value_forecast": 165010,
    "value_final": 163120,
    "value_discount": 1070,
    "value_budget": 162537,
    "value_customer": 163120,
    "value_bonus": 1491,
    "opportunityscl": "Final Acceptance:4%; Material Procurement Payment:7%; Installation Completion:33%; Delivery Payment:56%"
  },
  {
    "opportunityid": "OPP-00033",
    "opportunityname": "Cybersecurity Upgrade – Phase 2",
    "opportunitydescription": "Rollout of infrastructure modernization across multiple sites.",
    "customerid": "CS-CISCO-033",
    "customername": "Cisco Systems",
    "opportunitystatut": "Start",
    "hardware_price": 114991,
    "software_price": 78381,
    "service_price": 71559,
    "opportunityphase": "Deal",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 4,
    "swot_weakness": 1,
    "swot_opportunities": 5,
    "swot_threats": 4,
    "value_forecast": 267548,
    "value_final": 264931,
    "value_discount": 421,
    "value_budget": 263216,
    "value_customer": 264931,
    "value_bonus": 1600,
    "opportunityscl": "Material Procurement Payment:25%; Integration & Configuration Payment:51%; Delivery Payment:7%; Technical Acceptance Payment:16%"
  },
  {
    "opportunityid": "OPP-00034",
    "opportunityname": "SD-WAN Deployment – Phase 3",
    "opportunitydescription": "Migration of workloads to hybrid cloud environments.",
    "customerid": "CS-GCP-034",
    "customername": "Google Cloud",
    "opportunitystatut": "Forecast",
    "hardware_price": 37652,
    "software_price": 7650,
    "service_price": 41268,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Luca Moretti",
    "swot_strength": 3,
    "swot_weakness": 2,
    "swot_opportunities": 2,
    "swot_threats": 3,
    "value_forecast": 86582,
    "value_final": 86570,
    "value_discount": 3289,
    "value_budget": 82394,
    "value_customer": 86570,
    "value_bonus": 1638,
    "opportunityscl": "Delivery Payment:46%; Design Approval Payment:54%"
  },
  {
    "opportunityid": "OPP-00035",
    "opportunityname": "Storage Platform Upgrade – Phase 1",
    "opportunitydescription": "Modernizing core systems to enhance operational efficiency.",
    "customerid": "CS-CAPG-035",
    "customername": "Capgemini",
    "opportunitystatut": "Stop",
    "hardware_price": 105490,
    "software_price": 65806,
    "service_price": 118619,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Sofia Benali",
    "swot_strength": 1,
    "swot_weakness": 5,
    "swot_opportunities": 2,
    "swot_threats": 2,
    "value_forecast": 292720,
    "value_final": 289915,
    "value_discount": 1863,
    "value_budget": 286820,
    "value_customer": 289915,
    "value_bonus": 1641,
    "opportunityscl": "Material Procurement Payment:25%; Technical Acceptance Payment:75%"
  },
  {
    "opportunityid": "OPP-00036",
    "opportunityname": "Smart Facility Project – Phase 3",
    "opportunitydescription": "Rollout of infrastructure modernization across multiple sites.",
    "customerid": "CS-SG-036",
    "customername": "Société Générale",
    "opportunitystatut": "Stop",
    "hardware_price": 53998,
    "software_price": 56264,
    "service_price": 97586,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Youssef El-Haddad",
    "swot_strength": 2,
    "swot_weakness": 2,
    "swot_opportunities": 4,
    "swot_threats": 1,
    "value_forecast": 212008,
    "value_final": 207848,
    "value_discount": 107,
    "value_budget": 203783,
    "value_customer": 207848,
    "value_bonus": 1823,
    "opportunityscl": "Material Procurement Payment:18%; Down Payment:82%"
  },
  {
    "opportunityid": "OPP-00037",
    "opportunityname": "Storage Platform Upgrade – Phase 3",
    "opportunitydescription": "Implementing cybersecurity best practices and identity protections.",
    "customerid": "CS-OBS-037",
    "customername": "Orange Business Services",
    "opportunitystatut": "Forecast",
    "hardware_price": 26270,
    "software_price": 31934,
    "service_price": 26939,
    "opportunityphase": "Discovery",
    "opportunityowner": "Anna Kovács",
    "swot_strength": 3,
    "swot_weakness": 4,
    "swot_opportunities": 3,
    "swot_threats": 5,
    "value_forecast": 90120,
    "value_final": 85143,
    "value_discount": 386,
    "value_budget": 79625,
    "value_customer": 85143,
    "value_bonus": 2489,
    "opportunityscl": "Material Procurement Payment:57%; Down Payment:43%"
  },
  {
    "opportunityid": "OPP-00038",
    "opportunityname": "High Availability Deployment – Phase 3",
    "opportunitydescription": "Deployment of scalable infrastructure for improved performance.",
    "customerid": "CS-GCP-038",
    "customername": "Google Cloud",
    "opportunitystatut": "Stop",
    "hardware_price": 15147,
    "software_price": 64345,
    "service_price": 117030,
    "opportunityphase": "Deal",
    "opportunityowner": "Hugo Martin",
    "swot_strength": 1,
    "swot_weakness": 4,
    "swot_opportunities": 2,
    "swot_threats": 1,
    "value_forecast": 198534,
    "value_final": 196522,
    "value_discount": 405,
    "value_budget": 196130,
    "value_customer": 196522,
    "value_bonus": 93,
    "opportunityscl": "Design Approval Payment:44%; Down Payment:56%"
  },
  {
    "opportunityid": "OPP-00039",
    "opportunityname": "High Availability Deployment – Phase 1",
    "opportunitydescription": "Implementing cybersecurity best practices and identity protections.",
    "customerid": "CS-GCP-039",
    "customername": "Google Cloud",
    "opportunitystatut": "Start",
    "hardware_price": 122078,
    "software_price": 76834,
    "service_price": 32212,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Nadia Cherif",
    "swot_strength": 5,
    "swot_weakness": 4,
    "swot_opportunities": 3,
    "swot_threats": 1,
    "value_forecast": 234140,
    "value_final": 231124,
    "value_discount": 2113,
    "value_budget": 230203,
    "value_customer": 231124,
    "value_bonus": 1330,
    "opportunityscl": "Installation Completion:74%; Delivery Payment:26%"
  },
  {
    "opportunityid": "OPP-00040",
    "opportunityname": "Cybersecurity Upgrade – Phase 1",
    "opportunitydescription": "Deployment of scalable infrastructure for improved performance.",
    "customerid": "CS-HWE-040",
    "customername": "Huawei Enterprise",
    "opportunitystatut": "Forecast",
    "hardware_price": 62180,
    "software_price": 48958,
    "service_price": 79608,
    "opportunityphase": "Prospection",
    "opportunityowner": "Laura Schmidt",
    "swot_strength": 2,
    "swot_weakness": 5,
    "swot_opportunities": 3,
    "swot_threats": 5,
    "value_forecast": 193469,
    "value_final": 190746,
    "value_discount": 877,
    "value_budget": 185777,
    "value_customer": 190746,
    "value_bonus": 1900,
    "opportunityscl": "Installation Completion:82%; Final Acceptance:13%; Material Procurement Payment:6%"
  },
  {
    "opportunityid": "OPP-00041",
    "opportunityname": "Cybersecurity Upgrade – Phase 3",
    "opportunitydescription": "Implementing cybersecurity best practices and identity protections.",
    "customerid": "CS-SG-041",
    "customername": "Société Générale",
    "opportunitystatut": "Start",
    "hardware_price": 146851,
    "software_price": 56173,
    "service_price": 108761,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Elena Rossi",
    "swot_strength": 2,
    "swot_weakness": 5,
    "swot_opportunities": 3,
    "swot_threats": 5,
    "value_forecast": 313013,
    "value_final": 311785,
    "value_discount": 1218,
    "value_budget": 309372,
    "value_customer": 311785,
    "value_bonus": 2210,
    "opportunityscl": "Final Acceptance:73%; Down Payment:27%"
  },
  {
    "opportunityid": "OPP-00042",
    "opportunityname": "IoT Building Integration – Phase 1",
    "opportunitydescription": "Rollout of infrastructure modernization across multiple sites.",
    "customerid": "CS-GCP-042",
    "customername": "Google Cloud",
    "opportunitystatut": "Stop",
    "hardware_price": 87728,
    "software_price": 50776,
    "service_price": 85967,
    "opportunityphase": "Deal",
    "opportunityowner": "Elena Rossi",
    "swot_strength": 4,
    "swot_weakness": 3,
    "swot_opportunities": 4,
    "swot_threats": 3,
    "value_forecast": 226459,
    "value_final": 224471,
    "value_discount": 3961,
    "value_budget": 223810,
    "value_customer": 224471,
    "value_bonus": 322,
    "opportunityscl": "Final Acceptance:43%; Installation Completion:12%; Delivery Payment:46%"
  },
  {
    "opportunityid": "OPP-00043",
    "opportunityname": "IoT Building Integration – Phase 1",
    "opportunitydescription": "Modernizing core systems to enhance operational efficiency.",
    "customerid": "CS-OBS-043",
    "customername": "Orange Business Services",
    "opportunitystatut": "Cancelled",
    "hardware_price": 142882,
    "software_price": 81139,
    "service_price": 95868,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Hugo Martin",
    "swot_strength": 4,
    "swot_weakness": 3,
    "swot_opportunities": 2,
    "swot_threats": 3,
    "value_forecast": 325213,
    "value_final": 319889,
    "value_discount": 2965,
    "value_budget": 317389,
    "value_customer": 319889,
    "value_bonus": 1073,
    "opportunityscl": "Design Approval Payment:16%; Installation Completion:20%; Delivery Payment:64%"
  },
  {
    "opportunityid": "OPP-00044",
    "opportunityname": "Cloud Migration – Phase 4",
    "opportunitydescription": "Full upgrade of networking equipment and routing policies.",
    "customerid": "CS-CISCO-044",
    "customername": "Cisco Systems",
    "opportunitystatut": "Stop",
    "hardware_price": 27618,
    "software_price": 74490,
    "service_price": 16499,
    "opportunityphase": "Discovery",
    "opportunityowner": "Hugo Martin",
    "swot_strength": 2,
    "swot_weakness": 5,
    "swot_opportunities": 1,
    "swot_threats": 1,
    "value_forecast": 119774,
    "value_final": 118607,
    "value_discount": 677,
    "value_budget": 112852,
    "value_customer": 118607,
    "value_bonus": 1098,
    "opportunityscl": "Final Acceptance:12%; Material Procurement Payment:47%; Design Approval Payment:41%"
  },
  {
    "opportunityid": "OPP-00045",
    "opportunityname": "Smart Facility Project – Phase 3",
    "opportunitydescription": "Modernizing core systems to enhance operational efficiency.",
    "customerid": "CS-DELL-045",
    "customername": "Dell Technologies",
    "opportunitystatut": "Start",
    "hardware_price": 27256,
    "software_price": 57386,
    "service_price": 11446,
    "opportunityphase": "Discovery",
    "opportunityowner": "Elena Rossi",
    "swot_strength": 3,
    "swot_weakness": 3,
    "swot_opportunities": 3,
    "swot_threats": 4,
    "value_forecast": 100642,
    "value_final": 96088,
    "value_discount": 1835,
    "value_budget": 91048,
    "value_customer": 96088,
    "value_bonus": 1912,
    "opportunityscl": "Down Payment:77%; Technical Acceptance Payment:3%; Delivery Payment:20%"
  },
  {
    "opportunityid": "OPP-00046",
    "opportunityname": "IoT Building Integration – Phase 3",
    "opportunitydescription": "Enhancement of datacenter power, cooling and monitoring.",
    "customerid": "CS-AWS-046",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Stop",
    "hardware_price": 82595,
    "software_price": 24875,
    "service_price": 45092,
    "opportunityphase": "Deal",
    "opportunityowner": "Sofia Benali",
    "swot_strength": 1,
    "swot_weakness": 5,
    "swot_opportunities": 4,
    "swot_threats": 4,
    "value_forecast": 157076,
    "value_final": 152562,
    "value_discount": 3147,
    "value_budget": 147221,
    "value_customer": 152562,
    "value_bonus": 2245,
    "opportunityscl": "Final Acceptance:25%; Technical Acceptance Payment:7%; Integration & Configuration Payment:69%"
  },
  {
    "opportunityid": "OPP-00047",
    "opportunityname": "Zero Trust Program – Phase 3",
    "opportunitydescription": "Modernizing core systems to enhance operational efficiency.",
    "customerid": "CS-CISCO-047",
    "customername": "Cisco Systems",
    "opportunitystatut": "Forecast",
    "hardware_price": 38504,
    "software_price": 47665,
    "service_price": 51909,
    "opportunityphase": "Deal",
    "opportunityowner": "Luca Moretti",
    "swot_strength": 5,
    "swot_weakness": 1,
    "swot_opportunities": 3,
    "swot_threats": 2,
    "value_forecast": 140167,
    "value_final": 138078,
    "value_discount": 1784,
    "value_budget": 132362,
    "value_customer": 138078,
    "value_bonus": 650,
    "opportunityscl": "Installation Completion:3%; Down Payment:9%; Design Approval Payment:88%"
  },
  {
    "opportunityid": "OPP-00048",
    "opportunityname": "SD-WAN Deployment – Phase 4",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-CAPG-048",
    "customername": "Capgemini",
    "opportunitystatut": "Forecast",
    "hardware_price": 125651,
    "software_price": 5443,
    "service_price": 63846,
    "opportunityphase": "Discovery",
    "opportunityowner": "Sofia Benali",
    "swot_strength": 2,
    "swot_weakness": 4,
    "swot_opportunities": 5,
    "swot_threats": 5,
    "value_forecast": 196800,
    "value_final": 194940,
    "value_discount": 3759,
    "value_budget": 190992,
    "value_customer": 194940,
    "value_bonus": 1247,
    "opportunityscl": "Delivery Payment:17%; Final Acceptance:36%; Installation Completion:48%"
  },
  {
    "opportunityid": "OPP-00049",
    "opportunityname": "Cybersecurity Upgrade – Phase 1",
    "opportunitydescription": "Deployment of IoT-enabled building management systems.",
    "customerid": "CS-GCP-049",
    "customername": "Google Cloud",
    "opportunitystatut": "Forecast",
    "hardware_price": 15249,
    "software_price": 81762,
    "service_price": 79599,
    "opportunityphase": "Evaluation",
    "opportunityowner": "Luca Moretti",
    "swot_strength": 4,
    "swot_weakness": 5,
    "swot_opportunities": 2,
    "swot_threats": 5,
    "value_forecast": 181752,
    "value_final": 176610,
    "value_discount": 1407,
    "value_budget": 174694,
    "value_customer": 176610,
    "value_bonus": 180,
    "opportunityscl": "Down Payment:1%; Technical Acceptance Payment:99%"
  },
  {
    "opportunityid": "OPP-00050",
    "opportunityname": "High Availability Deployment – Phase 3",
    "opportunitydescription": "Migration of workloads to hybrid cloud environments.",
    "customerid": "CS-AWS-050",
    "customername": "Amazon Web Services",
    "opportunitystatut": "Start",
    "hardware_price": 139556,
    "software_price": 86592,
    "service_price": 37375,
    "opportunityphase": "Discovery",
    "opportunityowner": "Marc Dupont",
    "swot_strength": 4,
    "swot_weakness": 5,
    "swot_opportunities": 1,
    "swot_threats": 5,
    "value_forecast": 266941,
    "value_final": 263523,
    "value_discount": 438,
    "value_budget": 259852,
    "value_customer": 263523,
    "value_bonus": 121,
    "opportunityscl": "Delivery Payment:7%; Integration & Configuration Payment:47%; Final Acceptance:47%"
  }
] as const;

export const excelActions = [
  {
    "opportunityid": "OPP-00001",
    "title": "Data Center Modernization – Phase 1",
    "clientname": "Société Générale",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00002",
    "title": "Smart Facility Project – Phase 1",
    "clientname": "Dell Technologies",
    "currentaction": "En attente du lancement de la commande côté client",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00002",
    "title": "Smart Facility Project – Phase 1",
    "clientname": "Dell Technologies",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00003",
    "title": "Network Backbone Upgrade – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00003",
    "title": "Network Backbone Upgrade – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "Validation des profils en cours",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00004",
    "title": "Cloud Migration – Phase 2",
    "clientname": "Cisco Systems",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Nadia Cherif"
  },
  {
    "opportunityid": "OPP-00005",
    "title": "Data Center Modernization – Phase 1",
    "clientname": "Orange Business Services",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00006",
    "title": "Zero Trust Program – Phase 2",
    "clientname": "Huawei Enterprise",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Nadia Cherif"
  },
  {
    "opportunityid": "OPP-00007",
    "title": "Network Backbone Upgrade – Phase 1",
    "clientname": "Google Cloud",
    "currentaction": "En attente de réception du matériel",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00007",
    "title": "Network Backbone Upgrade – Phase 1",
    "clientname": "Google Cloud",
    "currentaction": "Validation des profils en cours",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00008",
    "title": "SD-WAN Deployment – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00008",
    "title": "SD-WAN Deployment – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00009",
    "title": "Smart Facility Project – Phase 2",
    "clientname": "SFR Business",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00010",
    "title": "IoT Building Integration – Phase 2",
    "clientname": "Huawei Enterprise",
    "currentaction": "Revue contractuelle interne en cours",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00011",
    "title": "SD-WAN Deployment – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "Planification technique avec l’équipe client",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00012",
    "title": "Compute Cluster Expansion – Phase 2",
    "clientname": "Cisco Systems",
    "currentaction": "En attente de la clarification technique",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00013",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "SFR Business",
    "currentaction": "En attente du lancement de la commande côté client",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00013",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "SFR Business",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00014",
    "title": "IoT Building Integration – Phase 1",
    "clientname": "Société Générale",
    "currentaction": "En attente de la clarification technique",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00014",
    "title": "IoT Building Integration – Phase 1",
    "clientname": "Société Générale",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00015",
    "title": "Storage Platform Upgrade – Phase 2",
    "clientname": "SFR Business",
    "currentaction": "Revue contractuelle interne en cours",
    "salesowner": "Nadia Cherif"
  },
  {
    "opportunityid": "OPP-00016",
    "title": "High Availability Deployment – Phase 2",
    "clientname": "Huawei Enterprise",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00017",
    "title": "High Availability Deployment – Phase 1",
    "clientname": "Amazon Web Services",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00018",
    "title": "Network Backbone Upgrade – Phase 2",
    "clientname": "Huawei Enterprise",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00019",
    "title": "Hybrid Cloud Deployment – Phase 2",
    "clientname": "Orange Business Services",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00020",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "Dell Technologies",
    "currentaction": "Validation des profils en cours",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00021",
    "title": "Zero Trust Program – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Nadia Cherif"
  },
  {
    "opportunityid": "OPP-00022",
    "title": "High Availability Deployment – Phase 1",
    "clientname": "Société Générale",
    "currentaction": "Planification technique avec l’équipe client",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00023",
    "title": "Data Center Modernization – Phase 1",
    "clientname": "Orange Business Services",
    "currentaction": "En attente de retour du fournisseur",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00023",
    "title": "Data Center Modernization – Phase 1",
    "clientname": "Orange Business Services",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00024",
    "title": "IoT Building Integration – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "Revue contractuelle interne en cours",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00024",
    "title": "IoT Building Integration – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00025",
    "title": "IoT Building Integration – Phase 2",
    "clientname": "Dell Technologies",
    "currentaction": "Revue contractuelle interne en cours",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00026",
    "title": "Compute Cluster Expansion – Phase 2",
    "clientname": "Huawei Enterprise",
    "currentaction": "En attente de la clarification technique",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00027",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "Amazon Web Services",
    "currentaction": "En attente de retour du fournisseur",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00028",
    "title": "SD-WAN Deployment – Phase 2",
    "clientname": "Google Cloud",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00028",
    "title": "SD-WAN Deployment – Phase 2",
    "clientname": "Google Cloud",
    "currentaction": "Planification technique avec l’équipe client",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00029",
    "title": "Hybrid Cloud Deployment – Phase 1",
    "clientname": "SFR Business",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00030",
    "title": "Cloud Migration – Phase 1",
    "clientname": "BNP Paribas",
    "currentaction": "En attente de réception du matériel",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00030",
    "title": "Cloud Migration – Phase 1",
    "clientname": "BNP Paribas",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00031",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "Capgemini",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00031",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "Capgemini",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00032",
    "title": "IoT Building Integration – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00032",
    "title": "IoT Building Integration – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00033",
    "title": "Network Backbone Upgrade – Phase 2",
    "clientname": "Cisco Systems",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00034",
    "title": "Storage Platform Upgrade – Phase 2",
    "clientname": "Google Cloud",
    "currentaction": "Revue contractuelle interne en cours",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00034",
    "title": "Storage Platform Upgrade – Phase 2",
    "clientname": "Google Cloud",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00035",
    "title": "Network Backbone Upgrade – Phase 2",
    "clientname": "Amazon Web Services",
    "currentaction": "En attente de réception du matériel",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00036",
    "title": "Data Center Modernization – Phase 2",
    "clientname": "Orange Business Services",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Omar Haddad"
  },
  {
    "opportunityid": "OPP-00037",
    "title": "High Availability Deployment – Phase 2",
    "clientname": "Dell Technologies",
    "currentaction": "Revue contractuelle interne en cours",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00038",
    "title": "Storage Platform Upgrade – Phase 2",
    "clientname": "Dell Technologies",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00039",
    "title": "Cybersecurity Upgrade – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "En attente du PO",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00039",
    "title": "Cybersecurity Upgrade – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "Planification technique avec l’équipe client",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00040",
    "title": "IoT Building Integration – Phase 2",
    "clientname": "Dell Technologies",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00040",
    "title": "IoT Building Integration – Phase 2",
    "clientname": "Dell Technologies",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00041",
    "title": "SD-WAN Deployment – Phase 2",
    "clientname": "Capgemini",
    "currentaction": "En attente du lancement de la commande côté client",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00042",
    "title": "Compute Cluster Expansion – Phase 1",
    "clientname": "Dell Technologies",
    "currentaction": "En attente de signature du contrat",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00042",
    "title": "Compute Cluster Expansion – Phase 1",
    "clientname": "Dell Technologies",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00043",
    "title": "Data Center Modernization – Phase 1",
    "clientname": "Amazon Web Services",
    "currentaction": "En attente de réception du matériel",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00044",
    "title": "Data Center Modernization – Phase 2",
    "clientname": "SFR Business",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00044",
    "title": "Data Center Modernization – Phase 2",
    "clientname": "SFR Business",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00045",
    "title": "Network Backbone Upgrade – Phase 1",
    "clientname": "Huawei Enterprise",
    "currentaction": "En attente du lancement de la commande côté client",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00045",
    "title": "Network Backbone Upgrade – Phase 1",
    "clientname": "Huawei Enterprise",
    "currentaction": "Phase de négociation commerciale",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00046",
    "title": "Cybersecurity Upgrade – Phase 1",
    "clientname": "Cisco Systems",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00047",
    "title": "Zero Trust Program – Phase 1",
    "clientname": "Dell Technologies",
    "currentaction": "Planification technique avec l’équipe client",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00048",
    "title": "Cloud Migration – Phase 2",
    "clientname": "Google Cloud",
    "currentaction": "En attente des autorisations gouvernementales",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00049",
    "title": "IoT Building Integration – Phase 1",
    "clientname": "Huawei Enterprise",
    "currentaction": "En attente de validation de l’offre",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00050",
    "title": "Cloud Migration – Phase 1",
    "clientname": "Capgemini",
    "currentaction": "Planification technique avec l’équipe client",
    "salesowner": "Omar Haddad"
  }
] as const;

export const excelAlerts = [
  {
    "opportunityname": "Data Center Modernization – Phase 2",
    "currentaction": "En attente de validation de l’offre",
    "delay_days": 10,
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityname": "Cloud Migration – Phase 1",
    "currentaction": "Matériel non reçu",
    "delay_days": 42,
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityname": "Network Backbone Upgrade – Phase 3",
    "currentaction": "En attente de validation de l’offre",
    "delay_days": 38,
    "salesowner": "Omar Haddad"
  },
  {
    "opportunityname": "SD-WAN Deployment – Phase 1",
    "currentaction": "Revue contractuelle bloquée",
    "delay_days": 8,
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityname": "Cybersecurity Upgrade – Phase 2",
    "currentaction": "Clarification technique en retard",
    "delay_days": 39,
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityname": "Hybrid Cloud Deployment – Phase 1",
    "currentaction": "En attente du lancement de la commande côté client",
    "delay_days": 6,
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityname": "IoT Building Integration – Phase 3",
    "currentaction": "Clarification technique en retard",
    "delay_days": 18,
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityname": "Zero Trust Security Program – Phase 2",
    "currentaction": "Négociation commerciale en attente",
    "delay_days": 11,
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityname": "Smart Facility Project – Phase 1",
    "currentaction": "Kickoff projet non planifié",
    "delay_days": 5,
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityname": "Storage Platform Upgrade – Phase 2",
    "currentaction": "En attente des autorisations gouvernementales",
    "delay_days": 28,
    "salesowner": "Marc Dupont"
  }
] as const;

export const excelNewsFeed = [
  {
    "opportunityid": "OPP-00003",
    "actioncompleted": "Offre commerciale envoyée",
    "clientname": "Orange Business Services",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00012",
    "actioncompleted": "Clarification technique finalisée",
    "clientname": "Société Générale",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00019",
    "actioncompleted": "Validation interne du contrat terminée",
    "clientname": "Cisco Systems",
    "salesowner": "Luca Moretti"
  },
  {
    "opportunityid": "OPP-00008",
    "actioncompleted": "Réunion de kickoff programmée",
    "clientname": "Dell Technologies",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00027",
    "actioncompleted": "Profiling technique approuvé",
    "clientname": "BNP Paribas",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00014",
    "actioncompleted": "PO reçu du client",
    "clientname": "Amazon Web Services",
    "salesowner": "Youssef El-Haddad"
  },
  {
    "opportunityid": "OPP-00031",
    "actioncompleted": "Proposition budgétaire ajustée",
    "clientname": "SFR Business",
    "salesowner": "Nadia Cherif"
  },
  {
    "opportunityid": "OPP-00005",
    "actioncompleted": "Étude d’impact technique validée",
    "clientname": "Huawei Enterprise",
    "salesowner": "Anna Kovács"
  },
  {
    "opportunityid": "OPP-00022",
    "actioncompleted": "Planification d’installation confirmée",
    "clientname": "Capgemini",
    "salesowner": "Elena Rossi"
  },
  {
    "opportunityid": "OPP-00017",
    "actioncompleted": "Check financier complété",
    "clientname": "Société Générale",
    "salesowner": "Marc Dupont"
  },
  {
    "opportunityid": "OPP-00044",
    "actioncompleted": "Préparation du dossier d’appel d’offres terminée",
    "clientname": "Google Cloud",
    "salesowner": "Omar Haddad"
  },
  {
    "opportunityid": "OPP-00039",
    "actioncompleted": "Matériel vérifié et prêt pour expédition",
    "clientname": "Orange Business Services",
    "salesowner": "Sofia Benali"
  },
  {
    "opportunityid": "OPP-00029",
    "actioncompleted": "Documentation technique remise au client",
    "clientname": "BNP Paribas",
    "salesowner": "Hugo Martin"
  },
  {
    "opportunityid": "OPP-00011",
    "actioncompleted": "Accord final obtenu du comité client",
    "clientname": "Dell Technologies",
    "salesowner": "Laura Schmidt"
  },
  {
    "opportunityid": "OPP-00050",
    "actioncompleted": "Configuration initiale validée par le client",
    "clientname": "SFR Business",
    "salesowner": "Luca Moretti"
  }
] as const;
